dist: trusty
sudo: false
language: csharp
matrix:
  include:
    - dotnet: 2.2.100
      mono: none
      env: DOTNETCORE=1
    - mono: latest
script:
  - git fetch --unshallow # in order to make Nerdbank.GitVersioning.Tasks.GetBuildVersion work
  - ./test-by-travis.sh
